# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JokesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JokesApp
  pod "common", :path => '../common/common.podspec'

  target 'JokesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JokesAppUITests' do
    # Pods for testing
  end

end
